---
# - name: Wordpress
#   import_tasks: wordpress.yml

- name: Copy Wordpress files
  ansible.builtin.copy:
    src: ./
    dest: /opt/cloud-1/wordpress/
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Build and start wordpress
  community.docker.docker_compose_v2:
    project_src: /opt/cloud-1
    services:
      - wordpress
    build: always
    state: present