---
# - name: Database
#   import_tasks: mariadb.yml

- name: Copy MariaDB files
  ansible.builtin.copy:
    src: ./
    dest: /opt/cloud-1/mariadb/
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Build and start mariadb
  community.docker.docker_compose_v2:
    project_src: /opt/cloud-1
    services:
      - mariadb
    build: always
    state: present