---
# - name: Database
#   import_tasks: mariadb.yml

- name: Copy MariaDB files
  ansible.builtin.copy:
    src: ./
    dest: /opt/cloud-1/mariadb/
    owner: ubuntu
    group: ubuntu
    mode: '0644'